### ISSUE TITLE
Conflict with ion-footer

### ISSUE THREAD

**Issue by juliocbcotta** [keephacking/ionic-hide-fab-onscroll#1]
hi, thanks for the project, it is helping me a lot!
I just found out that if I include the lib in the project all my `ion-footer` stops being kept in the bottom of the screen while scrolling. As a workaround I positioned them outside `ion-content`, but I don't know what other side effects may happen.
Hope to help.

**Comment by keephacking** [comment]
Actually thats what `ion-footer` will do , it is supposed to be after `ion-content` . What you need is `ion-toolbar` .That behaviour has nothing to do with the library .
